apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-frontend-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devops
      component: devops-frontend
  template:
    metadata:
      name: devops-frontend-deploy
      labels:
        app: devops
        component: devops-frontend
    spec:
      containers:
        - name: devops-frontend
          image: harbor.peppa-pig.top:8443/devops/devops-frontend:v1
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8081
            - name: prometheus
              containerPort: 9200

---
apiVersion: v1
kind: Service
metadata:
  name: devops-frontend-svc
  labels:
    app: devops
    component: devops-frontend
spec:
  type: NodePort
  ports:
    - port: 8081
      targetPort: http
      name: http
    - port: 9200
      targetPort: prometheus
      name: prometheus
